### ISSUE TITLE
R CMD CHECK warning and notes

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.modules.general#813]
```
* checking dependencies in R code ... WARNING
Missing or unexported object: ‘teal::ui_transform_teal_data’
```

```
* checking R code for possible problems ... [9s/7s] NOTE
srv_decorate_teal_data : <anonymous>: no visible global function
  definition for ‘srv_transform_teal_data’
Undefined global functions or variables:
  srv_transform_teal_data
```

```
* checking Rd cross-references ... NOTE
Found the following Rd file(s) with Rd \link{} targets missing package
anchors:
  tm_a_pca.Rd: teal_transform_module
  tm_a_regression.Rd: teal_transform_module
  tm_data_table.Rd: teal_transform_module
  tm_g_association.Rd: teal_transform_module
  tm_g_bivariate.Rd: teal_transform_module
  tm_g_distribution.Rd: teal_transform_module
  tm_g_response.Rd: teal_transform_module
  tm_g_scatterplot.Rd: teal_transform_module
  tm_g_scatterplotmatrix.Rd: teal_transform_module
  tm_missing_data.Rd: teal_transform_module
  tm_outliers.Rd: teal_transform_module
  tm_t_crosstable.Rd: teal_transform_module
Please provide package anchors for all Rd \link{} targets not in the
package itself and the base packages.
```

Observed for all(!) r-universe builds. Example: [Build and deploy / Build R-devel for Linux](https://github.com/r-universe/pharmaverse/actions/runs/12088562125/job/33712477123#logs)
